name: wekan-ondra
version: "0.22"
summary: The open-source Trello-like kanban
description: |
   Wekan is an open-source and collaborative kanban board application.

   Whether you’re maintaining a personal todo list, planning your holidays with some friends, or working in a team on your next revolutionary idea, Kanban boards are an unbeatable tool to keep your things organized. They give you a visual overview of the current state of your project, and make you productive by allowing you to focus on the few items that matter the most.
   Depending on target environment, some configuration settings might need to be adjusted.
   For full list of configuration options call:
   $ wekan-ondra.help

confinement: strict
grade: stable

architectures:
  - amd64

plugs:
  mongodb-plug:
    interface: content
    target: $SNAP_DATA/shared

slots:
  mongodb-slot:
    interface: content
    write:
      - $SNAP_DATA/share

apps:
    wekan:
        command: wekan-control
        daemon: simple
        plugs: [network, network-bind]

    mongodb:
        command: mongodb-control
        daemon: simple
        plugs: [network, network-bind]

    help:
        command: wekan-help

    database-backup:
        command: mongodb-backup
        plugs: [network, network-bind]

    database-list-backups:
        command: ls -ald $SNAP_COMMON/db-backups/*

    database-restore:
        command: mongodb-restore
        plugs: [network, network-bind]

parts:
    mongodb:
        source: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-3.4.3.tgz
        plugin: dump
        stage-packages: [libssl1.0.0]
        filesets:
            mongo:
                - usr
                - bin
                - lib
        stage:
            - $mongo
        prime:
            - $mongo

    wekan:
        source: https://github.com/wekan/wekan/releases/download/v0.22/wekan-0.22.tar.gz
        source-subdir: programs/server
        plugin: nodejs
        node-packages: [npm]
        node-engine: 4.8.1
        build-packages:
            - python
        install: |
            cp -r * $SNAPCRAFT_PART_INSTALL/
            cp .node_version.txt $SNAPCRAFT_PART_INSTALL/
        organize:
            README: README.wekan

    helpers:
        source: snap-src
        plugin: dump
        organize:
            wekan-control: bin/wekan-control
            mongodb-control: bin/mongodb-control
            wekan-read-settings: bin/wekan-read-settings
            wekan-help: bin/wekan-help
            mongodb-backup: bin/mongodb-backup
            mongodb-restore: bin/mongodb-restore
            config: bin/config
