#!/bin/sh

# store here all configuration options for wekan snap
SNAP_NAME="wekan-ondra"

# read configured settings first
SETTINGS_FILE="$SNAP_COMMON/wekan_settings.sh"
[ -f $SETTINGS_FILE ] && . $SETTINGS_FILE

# list of supported keys
keys="MONGODB_PORT MONGODB_BIND_IP MAIL_URL MAIL_FROM ROOT_URL PORT"

# default values
DESCRIPTION_MONGODB_PORT="mongodb binding port"
DEFAULT_MONGODB_PORT="27019"
KEY_MONGODB_PORT='mongodb-port'

DESCRIPTION_MONGODB_BIND_IP="mongodb binding address"
DEFAULT_MONGODB_BIND_IP="127.0.0.1"
KEY_MONGODB_BIND_IP="mongodb-bind-ip"

DESCRIPTION_MAIL_URL="wekan mail binding"
DEFAULT_MAIL_URL="smtp://user:pass@mailserver.examples.com:25/"
KEY_MAIL_URL="mail-url"

DESCRIPTION_MAIL_FROM="wekan's admin mail from name email address"
DEFAULT_MAIL_FROM="wekan-admin@example.com"
KEY_MAIL_FROM="mail-from"

DESCRIPTION_ROOT_URL="wekan's root url, eg http://127.0.0.1, https://example.com, https://wekan.example.com, http://example.com/wekan"
DEFAULT_ROOT_URL="http://127.0.0.1"
KEY_ROOT_URL="root-url"

DESCRIPTION_PORT="port wekan is exposed at"
DEFAULT_PORT="8080"
KEY_PORT="port"
