#!/bin/bash

# get wekan/mongo settings
source $SNAP/bin/wekan-read-settings

# make sure we have set minimum env variables for locale
if [ -z "$LANG" ]; then
    export LANG=en_US.UTF-8
fi

export LC_ALL=C

# start mongo deamon
if [ "x" == "x${MONGODB_BIND_IP}" ]; then
    echo "using  unix socket"
    mongod --dbpath $SNAP_COMMON --logpath $SNAP_COMMON/mongodb.log --logappend --journal --unixSocketPrefix $SNAP_DATA
else
    if [ "x" == "x${MONGODB_PORT}" ]; then
        echo "using bind ip"
        mongod --dbpath $SNAP_COMMON --logpath $SNAP_COMMON/mongodb.log --logappend --bind_ip $MONGODB_BIND_IP --journal
    else
        echo "using bind ip"
        mongod --dbpath $SNAP_COMMON --logpath $SNAP_COMMON/mongodb.log --logappend --bind_ip $MONGODB_BIND_IP --port $MONGODB_PORT --journal
    fi
fi
