#!/bin/bash

SYSTEMD_WEKAN_SERVICE="snap.${SNAP_NAME}.wekan"
SYSTEMD_MONGODB_SERVICE="snap.${SNAP_NAME}.mongodb"

# get wekan/mongo settings
source $SNAP/bin/wekan-read-settings

export NODE_PATH=$SNAP/bin
if [ "x" == "x$MONGODB_BIND_IP" ]; then
    export MONGO_URL="mongodb://$SNAP_DATA/mongodb-27017.sock"
    echo "Mongo bind ip not defined, using default Unix socket: $MONGO_URL"
else
    if [ "x" == "x$MONGODB_PORT" ]; then
        export MONGO_URL="mongodb://$MONGODB_BIND_IP/wekan"
    else
        export MONGO_URL="mongodb://$MONGODB_BIND_IP:$MONGODB_PORT/wekan"
    fi
fi

APPLICATION_DIRECTORY=$SNAP
APPLICATION_START=main.js
cd $APPLICATION_DIRECTORY
$NODE_PATH/node $APPLICATION_START
