#!/bin/bash

# get wekan/mongo settings
source $SNAP/bin/wekan-read-settings

# make sure we have set minimum env variables for locale
if [ -z "$LANG" ]; then
    export LANG=en_US.UTF-8
fi

export LC_ALL=C

# start mongodb backup
if [ "x" == "x${MONGODB_BIND_IP}" ]; then
    echo "using  unix socket, this is likely not gonna work: https://jira.mongodb.org/browse/TOOLS-620"
    echo "configure mongodb binding to ip bind instead"
    mongorestore --host $SNAP_DATA/mongodb-27017.sock -d wekan --gzip  --archive=$1
else
    if [ "x" == "x${MONGODB_PORT}" ]; then
        echo "using bind ip"
        mongorestore --host $MONGODB_BIND_IP -d wekan --gzip  --archive=$1
    else
        echo "using bind ip"
        mongorestore --host $MONGODB_BIND_IP --port $MONGODB_PORT -d wekan --gzip  --archive=$1
    fi
fi
