#!/bin/bash

# store here all configuration for wekan snap

# TODO: get rid of this workaround once above can be used
SETTINGS_FILE="$SNAP_COMMON/wekan_settings.sh"
[ -f $SETTINGS_FILE ] && source $SETTINGS_FILE

# list of supported keys
keys=("MONGODB_PORT" "MONGODB_BIND_IP" "MAIL_URL" "MAIL_FROM" "ROOT_URL" "PORT")

# default values
DESCRIPTION_MONGODB_PORT="mongodb binding port"
DEFAULT_MONGODB_PORT="27017"
DESCRIPTION_MONGODB_BIND_IP="mongodb binding address"
DEFAULT_MONGODB_BIND_IP="127.0.0.1"
DESCRIPTION_MAIL_URL="wekan mail binding"
DEFAULT_MAIL_URL="smtp://user:pass@mailserver.examples.com:25/"
DESCRIPTION_MAIL_FROM="wekan's admin mail from name email address"
DEFAULT_MAIL_FROM="wekan-admin@example.com"
DESCRIPTION_ROOT_URL="wekan's root url, eg http://127.0.0.1, https://example.com, https://wekan.example.com, http://example.com/wekan"
DEFAULT_ROOT_URL="http://127.0.0.1"
DESCRIPTION_PORT="port wekan is exposed at"
DEFAULT_PORT="8080"
