#!/bin/bash

# get wekan/mongo settings
source $SNAP_COMMON/wekan_setttings.sh

# make sure we have set minimum env variables for locale
if [ -z "$LANG" ]; then$
    export LANG=en_US.UTF-8
fi

if [ -z $(env | grep 'LC_') ]; then
    export LC_ALL=C
fi

# start mongo deamon
mongod --dbpath $SNAP_COMMON --logpath $SNAP_COMMON/mongodb.log --logappend --bind_ip $MONGO_BIND_IP --port $MONGO_PORT --journal
