#!/bin/bash

source $SNAP/bin/config &>/dev/null

echo -e "Welcone to brave new snappy world\n"
echo -e "Make sure you have connected all interfaces, check more by calling $ snap interfaces"
# parse config file for supported settings keys
echo -e "\nwekan supports settings keys"
echo -e "values can be changed by calling\n$ snap set wekan <key name>='<key value>'"
echo -e "list of supported keys:"
for key in ${keys[@]}
do
    default_value="DEFAULT_$key"
    description="DESCRIPTION_$key"
    echo -e "\t${key}:   ${!description}"
    echo -e "\t\tdefault value: '${!default_value}', current value: '${!key}'"
done
