#!/bin/sh

# mongodb binding port, MONGODB_PORT
DEFAULT_MONGODB_PORT="27017"
# mongodb binding address, MONGODB_BIND_IP
DEFAULT_MONGODB_BIND_IP="127.0.0.1"
# wekan mail binding, MAIL_URL
DEFAULT_MAIL_URL="smtp://user:pass@mailserver.examples.com:25/"
# wekan default mail from name
DEFAULT_MAIL_FROM="wekan-admin@example.com"
# wekan root url, ROOT_URL http://127.0.0.1(:8080), https://example.com, https://wekan.example.com, http://example.com/wekan,
DEFAULT_ROOT_URL="http://127.0.0.1"
DEFAULT_PORT="8080"
# list of supporting keys
keys=("MONGODB_PORT" "MONGODB_BIND_IP" "MAIL_URL" "MAIL_FROM" "ROOT_URL" "PORT")

# TODO: uncomment folling, once snapctl can be called from outside the hooks
# for key in ${keys[@]}
# do
#   if value=$(snapctl get $key); then
#       echo "$key='$value'"
#       export $key=$value
#   else
#       # use default value
#       default_value="DEFAULT_$key"
#       echo "using default value: $key=${!default_value}'"
#       export $key=${!default_value}
#   fi
# done

# TODO: get rid of this workaround once above can be used
SETTINGS_FILE="$SNAP_COMMON/wekan_settings.sh"
if [ -f $SETTINGS_FILE ]; then
    source $SETTINGS_FILE
fi

# loop through all values, and if not defined, use default value
for key in ${keys[@]}
do
  if [ -z "${!key}" ]; then
      # use default value
      default_value="DEFAULT_$key"
      echo "using default value: $key=${!default_value}'"
      export $key=${!default_value}
      # echo "export $key='${!def_value}'" >> $SETTINGS_FILE
  else
      echo "$key='${!key}'"
  fi

done
