#!/bin/sh

# read wekan config
source $SNAP/bin/config

# TODO: uncomment folling, once snapctl can be called from outside the hooks
# for key in ${keys[@]}
# do
#   if value=$(snapctl get $key); then
#       echo "$key='$value'"
#       export $key=$value
#   else
#       # use default value
#       default_value="DEFAULT_$key"
#       echo "using default value: $key=${!default_value}'"
#       export $key=${!default_value}
#   fi
# done

# TODO: get rid of this workaround once above can be used
# loop through all values, and if not defined, use default value
for key in ${keys[@]}
do
  if [ -z "${!key}" ]; then
      # use default value
      default_value="DEFAULT_$key"
      echo "using default value: $key='${!default_value}'"
      export $key=${!default_value}
      # echo "export $key='${!def_value}'" >> $SETTINGS_FILE
  else
      echo "$key='${!key}'"
  fi
done
